DROP DATABASE IF EXISTS escola;
CREATE DATABASE escola CHARSET=UTF8 COLLATE utf8_general_ci;
USE escola;

CREATE TABLE professore(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  especialidade VARCHAR(255)
);

CREATE TABLE aluno(
  ra VARCHAR(10) NOT NULL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  nascto DATE NOT NULL,
  idturma INT NOT NULL
);


CREATE TABLE turma(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nomeTurma VARCHAR(255) NOT NULL,
  sigla VARCHAR(255) NOT NULL
);

ALTER TABLE aluno ADD FOREIGN KEY (idturma) REFERENCES turma(id);

CREATE TABLE leciona(
  idturma INTEGER NOT NULL,
  idprofessor INTEGER NOT NULL,
  FOREIGN KEY (idturma) REFERENCES turma(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (idprofessor) REFERENCES professore(id) ON DELETE CASCADE ON UPDATE CASCADE
);